[functions.guide-verification]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.reset-admin-pass]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = true

[functions.generate-gpx]
verify_jwt = true

[functions.send-email]
verify_jwt = true
